### PR TITLE
Improve vision/detection mode management

### PR DESCRIPTION
**Pull request by dev7355608**

### CODE REVIEW

**Comment by dev7355608** [comment]
I should have added that this PR fixes the following bugs.

### Bug 1
https://github.com/stwlam/adequate-vision/blob/2852a6723e6f5aca72429f251179ebbaabeb055c/script.js#L149
Create a token without any actor senses, but give it Basic Vision and a Vision Range of 10. Now enable Adequate Vision: the token has 10 feet range of vision instead of 0.

### Bug 2
https://github.com/stwlam/adequate-vision/blob/2852a6723e6f5aca72429f251179ebbaabeb055c/script.js#L149
Create a token with Tremorsense 10 feet (actor senses) and give it Feel Tremor 10 feet. Now enable Adequate Vision: error because of typo (`mode` instead of `modes`) that breaks the entire thing:
```
foundry.js:747 ReferenceError: Error thrown in hooked function '' for hook 'ready'. mode is not defined
    at script.js:178:93
    at Array.some (<anonymous>)
    at updateTokens (script.js:178:44)
    at onReady (script.js:112:5)
    at Object.fn (script.js:58:3)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at Game.setupGame (foundry.js:7909:11)
    at async Game._initializeGameView (foundry.js:8964:5)
    at async Game.initialize (foundry.js:7782:5)
```

### Bug 3
https://github.com/stwlam/adequate-vision/blob/2852a6723e6f5aca72429f251179ebbaabeb055c/script.js#L184
Create a token with Darkvision 30 feet (actor senses), Blindsight 10 feet (actor senses), and no Tremorsense; give it Feel Tremor of 10 feet. Now enable Adequate Vision: token doesn't have blindsight because this line overrides `updates.detectionModes`.

### Bug 4
https://github.com/stwlam/adequate-vision/blob/2852a6723e6f5aca72429f251179ebbaabeb055c/script.js#L168
Create a token with Truesight 30 feet (actor senses). Token as a vision range of 30 feet as expected. Disable Link Actor Senses. Set the vision mode of the token to Devil's Sight. Re-enable Link Actor Senses. Token's vision range is 0.

### Bug 5
https://github.com/stwlam/adequate-vision/blob/2852a6723e6f5aca72429f251179ebbaabeb055c/script.js#L143
Create a token with Darkvision 30 feet (actor senses) and give the actor the Devil's Sight feat; set the Vision Range to 120. Enable Adequate Vision.  Token has a vision range of 120 feet with the Devil's Sight mode as expected. Disable Link Actor Senses. Set the vision mode of the token to Devil's Sight. Re-enable Link Actor Senses. The token's vision mode is Darkvision now.

**Comment by stwlam** [comment]
Could you separate out any bugfixes into separate PRs?

**Comment by dev7355608** [comment]
Except the hint change of Link Actor Senses and the minor cleanup in the `updateActor`/`updateToken` hooks all the changes in `updateTokens` are related thoses bugs. The new `updateTokens` just builds the update object and then diffs at the end to check whether an update are really needed. This eliminates all those bugs, which are related to manually checking for changes.

Merge #26 first; then I'll resolve the resulting conflicts here.

**Comment by stwlam** [comment]
Conflicts!

**Comment by dev7355608** [comment]
Resolved.

**Pull request merged**
